baseURL = 'https://olavopx.github.io/'
title = "Olavo Bilac's Blog"
theme = "gokarna"

defaultContentLanguage = "pt-br"
languageCode = 'pt-br'

enableRobotsTXT = true

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/olavopx"
    weight = 3
    pre = "<span data-feather='github'></span>"
    post = ""

[services]
  [services.disqus]
    shortname = 'olavodotpys-blog'

[params]
  accentColor = "#C0C0C0"
  footer = "Olavo Bilac A. Neto"

  numberPostsOnHomePage = 10
  showPostsOnHomePage = "recent"
  fontSize = "1.1rem"

  showBackToTopButton = true

  togglePreviousAndNextButtons = false

  avatarURL = "https://avatars.githubusercontent.com/u/137653930?s=400&u=743cfe951a0ede3c5e76bc0197fbcdd7d833ee5c&v=4"
  avatarSize = "size-m"  
  avatarAltText = "avatar"

  metaKeywords = [
      "blog",
      "gokarna",
      "hugo",
      "programador",
      "olavopx",
      "Olavo Bilac",
      "ações",
      "bolsa de valores",
      "B3",
      "developer",
      "ArchLinux",
      "linux",
  ]

  customFooterHTML = '''
    <div id="commento"></div>
    <script type="text/javascript" src="/disqus/coments.js" ></script>
  '''