baseURL = 'https://olavodotpy.github.io/'
defaultContentLanguage = "pt-br"
languageCode = 'en'
enableRobotsTXT = true
title = "Olavo Bilac's Blog"
theme = "gokarna"

[menu]
  [[menu.main]]
    # Display name
    name = "Posts"

    # Relative URL slug (appended to baseURL)
    url = "/posts/"

    # Lower weights are listed first in the menu (leftmost); higher weights are
    # listed last in the menu (rightmost)
    weight = 1

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    identifier = "github"

    url = "https://github.com/olavodotpy"
    weight = 3
    
    # Surround the menu entry (or name) with HTML content, such as Feather
    # icons: https://feathericons.com
    pre = "<span data-feather='github'></span>"
    post = ""

[services]
  [services.disqus]
    shortname = 'olavodotpys-blog'

[params]
  accentColor = "#C0C0C0"

  footer = "Olavo B. A. Neto"

  metaKeywords = ["blog", "gokarna", "hugo", "Programador", "olavodotpy", "Olavo Bilac", "Ações", "bolsa de valores", "B3", "Developer"]

  numberPostsOnHomePage = 10

  showPostsOnHomePage = "recent"

  togglePreviousAndNextButtons = false

  customFooterHTML = '''
    <div id="commento"></div>
    <script type="text/javascript" src="/disqus/coments.js" ></script>
'''