baseURL = 'https://olavodotpy.github.io/'
defaultContentLanguage = "pt-br"
languageCode = 'en'
enableRobotsTXT = true
title = "Olavo Bilac's Blog"
theme = "gokarna"

[menu]
  [[menu.main]]
    # Display name
    name = "Posts"

    # Relative URL slug (appended to baseURL)
    url = "/posts/"

    # Lower weights are listed first in the menu (leftmost); higher weights are
    # listed last in the menu (rightmost)
    weight = 1

    pre = "<img class='svg-inject' src='/book.svg' />"

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2

     pre = "<img class='svg-inject' src='/tag.svg' />"

  [[menu.main]]
    identifier = "github"

    url = "https://github.com/olavodotpy"
    weight = 3
    
    # Surround the menu entry (or name) with HTML content, such as Feather
    # icons: https://feathericons.com
    pre = "<span data-feather='github'></span>"
    post = ""

[services]
  [services.disqus]
    shortname = 'olavodotpys-blog'

[params]
  accentColor = "#C0C0C0"

  avatarURL = "https://avatars.githubusercontent.com/u/137653930?s=400&u=91a5a2db87e4ec6dfd60ce15574210de410e828f&v=4"

  avatarAltText = "olavodotpy"

  description = "“O universo pode não ser infinito, mas as possibilidades nele, essa é outra história” —Okabe Rintarou"

  footer = "Olavo B. A. Neto"

  metaKeywords = ["blog", "gokarna", "hugo", "Programador", "olavodotpy"]

  numberPostsOnHomePage = 2

  showPostsOnHomePage = "popular"

  togglePreviousAndNextButtons = false

  customFooterHTML = '''
    <div id="commento"></div>
    <script type="text/javascript" src="/js/disqus/coments.js" ></script>
'''
