# .github/workflows/hugo.yaml
name: Build and Deploy Hugo site

on:
  push:
    branches:
      - Master 

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true 

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v4
        with:
          hugo-version: "latest"

      - name: Build site
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: Master